// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Comment struct {
	ID            uint       `json:"id"`
	Content       string     `json:"content"`
	Author        *User      `json:"author"`
	CreatedAt     time.Time  `json:"createdAt"`
	Post          *Post      `json:"post"`
	ParentComment *Comment   `json:"parentComment,omitempty"`
	Replies       []*Comment `json:"replies"`
}

type Mutation struct {
}

type Post struct {
	ID        uint       `json:"id"`
	Title     string     `json:"title"`
	CreatedAt time.Time  `json:"createdAt"`
	Content   string     `json:"content"`
	Author    *User      `json:"author"`
	Comments  []*Comment `json:"comments"`
}

type Query struct {
}

type Subscription struct {
}

type User struct {
	ID       uint    `json:"id"`
	Username string  `json:"username"`
	Email    string  `json:"email"`
	Posts    []*Post `json:"posts"`
}
