package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"
	"errors"
	"fmt"
	"github.com/rmntim/ozon-task/internal/lib/logger/sl"
	"log/slog"

	"github.com/rmntim/ozon-task/graph"
	"github.com/rmntim/ozon-task/graph/model"
)

var (
	ErrInternal = errors.New("internal server error")
)

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, post model.PostInput) (*model.Post, error) {
	const op = "resolver.CreatePost"
	newPost, err := r.db.CreatePost(ctx, post)
	if err != nil {
		r.log.Error("internal server error", slog.String("op", op), sl.Err(err))
		return nil, ErrInternal
	}
	return newPost, nil
}

// CreateComment is the resolver for the createComment field.
func (r *mutationResolver) CreateComment(ctx context.Context, postID int, comment model.CommentInput) (*model.Comment, error) {
	panic(fmt.Errorf("not implemented: CreateComment - createComment"))
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id int) (*model.Post, error) {
	const op = "resolver.Post"
	post, err := r.db.GetPostById(ctx, id)
	if err != nil {
		r.log.Error("internal server error", slog.String("op", op), sl.Err(err))
		return nil, ErrInternal
	}
	return post, nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context, limit *int, offset *int) ([]*model.Post, error) {
	panic(fmt.Errorf("not implemented: Posts - posts"))
}

// Comment is the resolver for the comment field.
func (r *queryResolver) Comment(ctx context.Context, id int) (*model.Comment, error) {
	panic(fmt.Errorf("not implemented: Comment - comment"))
}

// CommentsForPost is the resolver for the commentsForPost field.
func (r *queryResolver) CommentsForPost(ctx context.Context, postID int) ([]*model.Comment, error) {
	panic(fmt.Errorf("not implemented: CommentsForPost - commentsForPost"))
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
